// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extension.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "extension.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace NEgoProto {

namespace {


}  // namespace


void protobuf_AssignDesc_extension_2eproto() {
  protobuf_AddDesc_extension_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "extension.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_extension_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_extension_2eproto() {
}

void protobuf_AddDesc_extension_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017extension.proto\022\tNEgoProto\032 google/pro"
    "tobuf/descriptor.proto:4\n\013description\022\035."
    "google.protobuf.FieldOptions\030\267\335\003 \001(\t:5\n\014"
    "short_option\022\035.google.protobuf.FieldOpti"
    "ons\030\270\335\003 \001(\t:6\n\rdefault_value\022\035.google.pr"
    "otobuf.FieldOptions\030\271\335\003 \001(\t", 227);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "extension.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    61111, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    61112, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    61113, 9, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_extension_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_extension_2eproto {
  StaticDescriptorInitializer_extension_2eproto() {
    protobuf_AddDesc_extension_2eproto();
  }
} static_descriptor_initializer_extension_2eproto_;
const ::std::string description_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  description(kDescriptionFieldNumber, description_default);
const ::std::string short_option_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  short_option(kShortOptionFieldNumber, short_option_default);
const ::std::string default_value_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  default_value(kDefaultValueFieldNumber, default_value_default);

// @@protoc_insertion_point(namespace_scope)

}  // namespace NEgoProto

// @@protoc_insertion_point(global_scope)
