// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extension.proto

#ifndef PROTOBUF_extension_2eproto__INCLUDED
#define PROTOBUF_extension_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

namespace NEgoProto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_extension_2eproto();
void protobuf_AssignDesc_extension_2eproto();
void protobuf_ShutdownFile_extension_2eproto();


// ===================================================================


// ===================================================================

static const int kDescriptionFieldNumber = 61111;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  description;
static const int kShortOptionFieldNumber = 61112;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  short_option;
static const int kDefaultValueFieldNumber = 61113;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  default_value;

// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace NEgoProto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_extension_2eproto__INCLUDED
