EXECUTE_PROCESS(
    COMMAND ${CMAKE_CTEST_COMMAND} -R ${TEST}
    RESULT_VARIABLE RESULT
    OUTPUT_VARIABLE OUT
    ERROR_VARIABLE ERR
)
IF(NOT RESULT EQUAL 0)
    FILE(REMOVE ${TARGET})
    MESSAGE(FATAL_ERROR "Test ${TEST} [${TARGET}] failed: ${OUT} ${ERR}")
ENDIF()
